baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "../themes/docdock"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeStyle = "original"
editURL = "https://github.com/worksonarm/worksonarm-news/tree/master/content/"

